import jsPDF from 'jspdf';
import type { AssessmentResults } from '@/types/assessment';

export function exportToPDF(results: AssessmentResults, language: 'en' | 'es' = 'en') {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let currentY = 20;

  // Title
  pdf.setFontSize(24);
  pdf.setTextColor(37, 99, 235); // Primary color
  const title = language === 'en' ? 'Your Ikigai Analysis' : 'Tu Análisis Ikigai';
  pdf.text(title, pageWidth / 2, currentY, { align: 'center' });
  currentY += 20;

  // Subtitle
  pdf.setFontSize(12);
  pdf.setTextColor(100, 100, 100);
  const subtitle = language === 'en' 
    ? 'Discover your reason for being with AI-powered career guidance'
    : 'Descubre tu razón de ser con orientación profesional impulsada por IA';
  pdf.text(subtitle, pageWidth / 2, currentY, { align: 'center' });
  currentY += 30;

  // Core Drivers Section
  pdf.setFontSize(18);
  pdf.setTextColor(0, 0, 0);
  const driversTitle = language === 'en' ? 'Core Drivers' : 'Impulsores Principales';
  pdf.text(driversTitle, 20, currentY);
  currentY += 15;

  // Energy
  pdf.setFontSize(14);
  pdf.setTextColor(37, 99, 235);
  const energyTitle = language === 'en' ? '🌟 Energy (What You Love)' : '🌟 Energía (Lo Que Amas)';
  pdf.text(energyTitle, 20, currentY);
  currentY += 8;
  
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  const energyText = pdf.splitTextToSize(results.analysis.energy, pageWidth - 40);
  pdf.text(energyText, 20, currentY);
  currentY += energyText.length * 5 + 10;

  // Edge
  pdf.setFontSize(14);
  pdf.setTextColor(124, 58, 237); // Secondary color
  const edgeTitle = language === 'en' ? '⚡ Edge (What You\'re Good At)' : '⚡ Ventaja (En Lo Que Eres Bueno)';
  pdf.text(edgeTitle, 20, currentY);
  currentY += 8;
  
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  const edgeText = pdf.splitTextToSize(results.analysis.edge, pageWidth - 40);
  pdf.text(edgeText, 20, currentY);
  currentY += edgeText.length * 5 + 10;

  // Impact
  pdf.setFontSize(14);
  pdf.setTextColor(16, 185, 129); // Success color
  const impactTitle = language === 'en' ? '🌍 Impact (What the World Needs)' : '🌍 Impacto (Lo Que El Mundo Necesita)';
  pdf.text(impactTitle, 20, currentY);
  currentY += 8;
  
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  const impactText = pdf.splitTextToSize(results.analysis.impact, pageWidth - 40);
  pdf.text(impactText, 20, currentY);
  currentY += impactText.length * 5 + 10;

  // Economic
  pdf.setFontSize(14);
  pdf.setTextColor(245, 158, 11); // Accent color
  const economicTitle = language === 'en' ? '💰 Economic Reality' : '💰 Realidad Económica';
  pdf.text(economicTitle, 20, currentY);
  currentY += 8;
  
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  const economicText = pdf.splitTextToSize(results.analysis.economic, pageWidth - 40);
  pdf.text(economicText, 20, currentY);
  currentY += economicText.length * 5 + 20;

  // Check if we need a new page
  if (currentY > pageHeight - 100) {
    pdf.addPage();
    currentY = 20;
  }

  // Purpose Paths Section
  pdf.setFontSize(18);
  pdf.setTextColor(0, 0, 0);
  const pathsTitle = language === 'en' ? 'Your Purpose Paths' : 'Tus Caminos de Propósito';
  pdf.text(pathsTitle, 20, currentY);
  currentY += 15;

  results.purposePaths.forEach((path, index) => {
    // Check if we need a new page
    if (currentY > pageHeight - 80) {
      pdf.addPage();
      currentY = 20;
    }

    pdf.setFontSize(14);
    pdf.setTextColor(37, 99, 235);
    pdf.text(`${index + 1}. ${path.title}`, 20, currentY);
    currentY += 10;

    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);
    const descText = pdf.splitTextToSize(path.description, pageWidth - 40);
    pdf.text(descText, 20, currentY);
    currentY += descText.length * 5 + 8;

    const strategyText = pdf.splitTextToSize(`Action Strategy: ${path.actionStrategy}`, pageWidth - 40);
    pdf.text(strategyText, 20, currentY);
    currentY += strategyText.length * 5 + 15;
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  const footer = language === 'en' 
    ? 'Generated by Purpose Finder - Powered by Nami AI'
    : 'Generado por Buscador de Propósito - Desarrollado por Nami AI';
  pdf.text(footer, pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  const filename = language === 'en' ? 'ikigai-analysis.pdf' : 'analisis-ikigai.pdf';
  pdf.save(filename);
}
