/**
* @description
* This file defines the complete database schema for the Purpose Finder application using Drizzle ORM.
* It includes table definitions, relationships, and Zod schemas for data validation and type inference.
* This schema is the single source of truth for all data structures shared between the server and client.
*
* The schema is designed to be normalized, separating concerns into distinct tables:
* - `assessment_sessions`: The core table for a user's journey.
* - `purpose_paths`: The three AI-generated career paths for a session.
* - `salary_data`: Salary benchmarks for each career path, fetched from the web.
* - `chat_messages`: A log of all interactions with the Nami AI assistant.
*
* @dependencies
* - drizzle-orm: Used for defining the database schema and relationships.
* - drizzle-zod: Used for generating Zod schemas from the Drizzle schema for validation.
* - zod: Used for defining custom validation schemas.
*/

import {
pgTable,
text,
serial,
integer,
jsonb,
timestamp,
pgEnum,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";

// ENUMs for specific text fields to enforce constraints
export const languageEnum = pgEnum("language_enum", ["en", "es"]);
export const chatRoleEnum = pgEnum("chat_role_enum", ["user", "assistant"]);
export const chatContextEnum = pgEnum("chat_context_enum", [
"discovery",
"action_plan",
]);

// ========= Table Definitions =========

/**
* @table assessment_sessions
* @description Stores the top-level information for a single user assessment session.
* It links together the user's questionnaire responses, the AI's analysis,
* the chosen career path, and the final action plan.
*/
export const assessmentSessions = pgTable("assessment_sessions", {
id: serial("id").primaryKey(),
sessionId: text("session_id").notNull().unique(),
language: languageEnum("language").notNull(),
responses: jsonb("responses"), // The initial questionnaire answers
coreDriversAnalysis: jsonb("core_drivers_analysis"), // Replaces the old 'analysis' field
chosenPathId: integer("chosen_path_id"), // FK to purpose_paths.id, nullable
actionPlan: jsonb("action_plan"), // The detailed step-by-step plan
createdAt: timestamp("created_at", { withTimezone: true })
.notNull()
.defaultNow(),
updatedAt: timestamp("updated_at", { withTimezone: true })
.notNull()
.defaultNow(),
});

/**
* @table purpose_paths
* @description Stores the three distinct "Purpose Paths" generated by the AI for a given session.
* Each path is linked back to its assessment session.
*/
export const purposePaths = pgTable("purpose_paths", {
id: serial("id").primaryKey(),
assessmentId: integer("assessment_id")
.notNull()
.references(() => assessmentSessions.id, { onDelete: "cascade" }),
title: text("title").notNull(),
description: text("description"),
ikigaiAlignment: jsonb("ikigai_alignment"), // JSON object with { love, goodAt, worldNeeds, pay }
actionStrategy: text("action_strategy"),
});

/**
* @table salary_data
* @description Stores salary benchmark information for a specific purpose path.
* This data is fetched using real-time web search.
*/
export const salaryData = pgTable("salary_data", {
id: serial("id").primaryKey(),
pathId: integer("path_id")
.notNull()
.references(() => purposePaths.id, { onDelete: "cascade" }),
entryLevel: text("entry_level"),
midLevel: text("mid_level"),
seniorLevel: text("senior_level"),
location: text("location"),
sources: text("sources").array(),
retrievedAt: timestamp("retrieved_at", { withTimezone: true })
.notNull()
.defaultNow(),
});

/**
* @table chat_messages
* @description Stores the entire history of a chat conversation for a session.
* The `context` field allows for filtering conversations related to either the
* initial "discovery" phase or the "action plan" refinement phase.
*/
export const chatMessages = pgTable("chat_messages", {
id: serial("id").primaryKey(),
assessmentId: integer("assessment_id")
.notNull()
.references(() => assessmentSessions.id, { onDelete: "cascade" }),
role: chatRoleEnum("role").notNull(),
content: text("content").notNull(),
context: chatContextEnum("context").notNull(),
createdAt: timestamp("created_at", { withTimezone: true })
.notNull()
.defaultNow(),
});

// ========= Drizzle Relations =========

export const assessmentSessionRelations = relations(
assessmentSessions,
({ one, many }) => ({
purposePaths: many(purposePaths),
chatMessages: many(chatMessages),
chosenPath: one(purposePaths, {
fields: [assessmentSessions.chosenPathId],
references: [purposePaths.id],
}),
}),
);

export const purposePathRelations = relations(
purposePaths,
({ one, many }) => ({
assessmentSession: one(assessmentSessions, {
fields: [purposePaths.assessmentId],
references: [assessmentSessions.id],
}),
salaryData: many(salaryData),
}),
);

export const salaryDataRelations = relations(salaryData, ({ one }) => ({
purposePath: one(purposePaths, {
fields: [salaryData.pathId],
references: [purposePaths.id],
}),
}));

export const chatMessageRelations = relations(chatMessages, ({ one }) => ({
assessmentSession: one(assessmentSessions, {
fields: [chatMessages.assessmentId],
references: [assessmentSessions.id],
}),
}));

// ========= Zod Schemas & Types =========

// Schemas for Database Inserts/Selects (Type-safe)
export const insertAssessmentSessionSchema =
createInsertSchema(assessmentSessions);
export const selectAssessmentSessionSchema =
createSelectSchema(assessmentSessions);

export const insertPurposePathSchema = createInsertSchema(purposePaths);
export const selectPurposePathSchema = createSelectSchema(purposePaths);

export const insertSalaryDataSchema = createInsertSchema(salaryData);
export const selectSalaryDataSchema = createSelectSchema(salaryData);

export const insertChatMessageSchema = createInsertSchema(chatMessages);
export const selectChatMessageSchema = createSelectSchema(chatMessages);

// Inferred Types for use in application code
export type AssessmentSession = typeof assessmentSessions.$inferSelect;
export type InsertAssessmentSession = typeof assessmentSessions.$inferInsert;
export type PurposePath = typeof purposePaths.$inferSelect;
export type InsertPurposePath = typeof purposePaths.$inferInsert;
export type SalaryData = typeof salaryData.$inferSelect;
export type InsertSalaryData = typeof salaryData.$inferInsert;
export type ChatMessage = typeof chatMessages.$inferSelect;
export type InsertChatMessage = typeof chatMessages.$inferInsert;

// ========= API Validation Schemas =========

// Base schema for questionnaire responses
export const questionnaireResponsesSchema = z.object({
passions: z.object({
activities: z.string().min(1),
topics: z.array(z.string()).min(1),
energizing: z.string().min(1),
}),
skills: z.object({
strengths: z.array(z.string()).min(1),
achievements: z.string().min(1),
feedback: z.string().min(1),
}),
values: z.object({
workValues: z.array(z.string()).min(1),
impact: z.string().min(1),
environment: z.string().min(1),
}),
economic: z.object({
salaryExpectation: z.string().min(1),
timeline: z.string().min(1),
stability: z.string().min(1),
}),
});
export type QuestionnaireResponses = z.infer<typeof questionnaireResponsesSchema>;

// **FIX**: Export the Language type so it can be imported by other modules.
export type Language = z.infer<typeof languageEnum.enum>;

// Schema for the /api/analyze endpoint
export const analysisRequestSchema = z.object({
sessionId: z.string().min(1),
language: z.enum(["en", "es"]),
responses: questionnaireResponsesSchema,
});
export type AnalysisRequest = z.infer<typeof analysisRequestSchema>;

// Schema for selecting a path and requesting an action plan
export const actionPlanRequestSchema = z.object({
sessionId: z.string().min(1),
chosenPathId: z.number(),
});
export type ActionPlanRequest = z.infer<typeof actionPlanRequestSchema>;

// Schema for chat messages, now with context
export const chatRequestSchema = z.object({
sessionId: z.string().min(1),
message: z.string().min(1),
context: z.enum(["discovery", "action_plan"]),
});
export type ChatRequest = z.infer<typeof chatRequestSchema>;

// Generic ActionState for consistent API responses
export type ActionState<T> =
| { isSuccess: true; message:string; data: T }
| { isSuccess: false; message: string; data?: never };