/**
 * @file action-plan-pdf.tsx
 * @description Full Action Plan PDF document component.
 * Generates a styled PDF matching the app's action plan page design.
 */

import { Document, Page, View, Text, StyleSheet, pdf } from '@react-pdf/renderer';
import type { ActionPlan } from '@/types/assessment';
import type { Language } from '@/lib/i18n';
import { t } from '@/lib/i18n';
import { IKIGAI_COLORS } from '../shared/colors';
import { MilestonePDF } from './milestone-pdf';

// Import fonts (side effect registration)
import '../shared/fonts';

const styles = StyleSheet.create({
  page: {
    backgroundColor: IKIGAI_COLORS.beige,
    padding: 40,
    fontFamily: 'Helvetica',
  },

  // Header section with blue background
  headerContainer: {
    backgroundColor: IKIGAI_COLORS.teal,
    marginHorizontal: -40,
    marginTop: -40,
    marginBottom: 24,
    padding: 24,
  },
  title: {
    fontFamily: 'Helvetica-Bold',
    fontSize: 24,
    color: IKIGAI_COLORS.white,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontFamily: 'Helvetica',
    fontSize: 12,
    color: IKIGAI_COLORS.white,
    textAlign: 'center',
    opacity: 0.9,
  },

  // Milestones container
  milestonesContainer: {
    flexDirection: 'column',
    gap: 16,
  },

  // Footer
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontFamily: 'Helvetica',
    fontSize: 9,
    color: IKIGAI_COLORS.slate500,
  },
});

interface ActionPlanPDFProps {
  actionPlan: ActionPlan;
  chosenPathTitle: string;
  language: Language;
}

function ActionPlanPDF({ actionPlan, chosenPathTitle, language }: ActionPlanPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        {/* Header with teal background */}
        <View style={styles.headerContainer}>
          <Text style={styles.title}>{t('actionPlan.title', language)}</Text>
          <Text style={styles.subtitle}>
            {t('actionPlan.chosenPath', language)}: {chosenPathTitle}
          </Text>
        </View>

        {/* Milestones */}
        <View style={styles.milestonesContainer}>
          {actionPlan.milestones.map((milestone, index) => (
            <MilestonePDF
              key={index}
              milestone={milestone}
              index={index}
              language={language}
            />
          ))}
        </View>

        {/* Footer */}
        <Text style={styles.footer} fixed>
          Generated by Revelio
        </Text>
      </Page>
    </Document>
  );
}

/**
 * Generates and downloads the Action Plan PDF.
 * Uses dynamic rendering with react-pdf's pdf() function.
 */
export async function generateActionPlanPDF(
  actionPlan: ActionPlan,
  chosenPathTitle: string,
  language: Language
): Promise<void> {
  const blob = await pdf(
    <ActionPlanPDF
      actionPlan={actionPlan}
      chosenPathTitle={chosenPathTitle}
      language={language}
    />
  ).toBlob();

  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download =
    language === 'en'
      ? 'purpose-finder-action-plan.pdf'
      : 'purpose-finder-plan-de-accion.pdf';
  link.click();

  // Cleanup
  URL.revokeObjectURL(url);
}
